import openai
import os
import streamlit as st

openai.api_key = os.getenv("OPENAI_API_KEY")

def ask_question(question):
    prompt = f"Q: {question}\nA:"
    response = openai.Completion.create(
        engine="text-davinci-003", 
        prompt=prompt,
        max_tokens=1024,
        n=1,
        stop=None,
        temperature=0.5,
    )
    answer = response.choices[0].text.strip()
    return answer

def main():
    st.title("OpenAI FAQ Chatbot")
    st.write("Welcome to the chatbot! Below are some frequently asked questions with their corresponding answers generated by OpenAI.")
    
    # Print common questions and their answers
    question1 = "What are the work hours?"
    answer1 = ask_question(question1)
    st.write(f"Q: {question1}\nA: {answer1}")
    
    question2 = "What are the company policies regarding sick leave?"
    answer2 = ask_question(question2)
    st.write(f"Q: {question2}\nA: {answer2}")
    
    question3 = "What is the dress code?"
    answer3 = ask_question(question3)
    st.write(f"Q: {question3}\nA: {answer3}")
    
    question4 = "What are the benefits offered by the company?"
    answer4 = ask_question(question4)
    st.write(f"Q: {question4}\nA: {answer4}")
    
    question5 = "Who do I contact if I have a question or concern?"
    answer5 = ask_question(question5)
    st.write(f"Q: {question5}\nA: {answer5}")
    
    question6 = "How often do performance evaluations occur?"
    answer6 = ask_question(question6)
    st.write(f"Q: {question6}\nA: {answer6}")
    
    # Allow user to ask additional questions
    st.write("\nIf you have any other questions, please enter them below:")
    user_input = st.text_input("Enter a question or type 'quit' to exit:")
    
    while user_input != "quit":
        if user_input:
            answer = ask_question(user_input)
            st.write(f"A: {answer}")
        user_input = st.text_input("Enter a question or type 'quit' to exit:")

if __name__ == "__main__":
    main()
