import streamlit as st
import openai

# Set OpenAI API key from Streamlit secrets
openai.api_key = st.secrets["OPENAI_API_KEY"]

def ask_question(question):
    prompt = f"Q: {question}\nA:"
    response = openai.Completion.create(
        engine="davinci",
        prompt=prompt,
        max_tokens=1024,
        n=1,
        stop=None,
        temperature=0.7,
    )
    answer = response.choices[0].text.strip()
    return answer

st.title("OpenAI Q&A Demo")

st.write("Welcome to the company! Below are the frequently asked questions with their corresponding answers generated by OpenAI.")
st.write("If you wish to ask another question, you can type it in the textbox below.")

# Print common questions and their answers
questions = [
    "What are the work hours?",
    "What are the company policies regarding sick leave?",
    "What is the dress code?",
    "What are the benefits offered by the company?",
    "Who do I contact if I have a question or concern?",
    "How often do performance evaluations occur?",
]

for question in questions:
    answer = ask_question(question)
    st.write(f"Q: {question}")
    st.write(f"A: {answer}")
    st.write("---")

# Allow user to ask their own questions
while True:
    user_question = st.text_input("Enter your question:")
    if user_question:
        answer = ask_question(user_question)
        st.write(f"Q: {user_question}")
        st.write(f"A: {answer}")
        st.write("---")
    else:
        break

st.write("Thank you for using the Q&A demo!")
